# Change to true for Disqus comments
#disqus:
  #comments: false
  #disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'UA-116898648-2'

menu:
#- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Home', path: '#'}
- {name: 'Blog', path: 'blog'}

#- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/thekage91'}
- {icon: 'twitter', link: 'https://twitter.com/00taffe'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/davidesicignani/'}
- {icon: 'instagram', link: 'http://www.linkedin.com/in/davidesicignani/'}

- {icon: 'envelope', link: 'mailto:davide@sprintstudio.co'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Next'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Read also:'

post_date_prefix: 'Written on'
